In [1]:
%matplotlib inline
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [21]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import xlrd
from sklearn.neural_network import MLPClassifier

In [22]:
# Load the excel data using pandas into a data frame with a reference to sheet name
xl_file = pd.read_excel(open('data/neural_network.xlsx','rb'), sheetname='Data')
xl_file.head()

Years  Salary  Used Credit
0      4      43            0
1     18      65            1
2      1      53            0
3      3      95            0
4     15      88            1

In [44]:
x = xl_file['Years'].tolist()
x

[4, 18, 1, 3, 15, 6]

In [45]:
y = xl_file['Salary'].tolist()
y

[43, 65, 53, 95, 88, 112]

In [50]:
mlp = MLPClassifier(hidden_layer_sizes=(6,6,6))
x_fit = np.reshape(x, (6,1))
x_fit

array([[ 4],
       [18],
       [ 1],
       [ 3],
       [15],
       [ 6]])

In [57]:
mlp = MLPClassifier(hidden_layer_sizes=(6,1))
mlp.fit(x_fit,y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(6, 1), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [61]:
predictions = mlp.predict(x_fit)
predictions

array([88, 65, 88, 88, 53, 53])

In [59]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y,predictions))

[[0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]]


In [60]:
print(classification_report(y,predictions))

             precision    recall  f1-score   support

         43       0.00      0.00      0.00         1
         53       0.00      0.00      0.00         1
         65       1.00      1.00      1.00         1
         88       0.00      0.00      0.00         1
         95       0.00      0.00      0.00         1
        112       0.00      0.00      0.00         1

avg / total       0.17      0.17      0.17         6

